# Let the unprivileged HexagonRPC daemon update the emulated Android persist tree.
d /usr/share/qcom/sm8550/Xiaomi/sheng/persist 0755 hexagonrpc hexagonrpc -
Z /usr/share/qcom/sm8550/Xiaomi/sheng/persist - hexagonrpc hexagonrpc -
